global:
  scrape_interval: 30s
  evaluation_interval: 30s
  scrape_timeout: 5s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - /config/rules.yaml

scrape_configs:
  #  - job_name: app
  #    static_configs:
  #      - targets:
  #          - app:8000
  - job_name: app
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
      - source_labels:
          - __meta_docker_container_label_com_docker_compose_project
          - __meta_docker_container_label_com_docker_compose_service
        separator: ;
        regex: "prometheus-stack;app"
        action: keep
      - source_labels:
          - __meta_docker_network_ip
        target_label: __address__
        action: replace
        replacement: "$1:8000"
      - source_labels:
          - __meta_docker_container_name
        target_label: container_name
        regex: /(.*)
        action: replace
    metric_relabel_configs:
      - source_labels:
          - status
        target_label: status_text
        regex: "200"
        replacement: OK
      - source_labels:
          - status
        target_label: status_text
        regex: "500"
        replacement: Internal Server Error
  - job_name: node-exporter
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
      - source_labels:
          - __meta_docker_container_label_com_docker_compose_project
          - __meta_docker_container_label_com_docker_compose_service
        separator: ;
        regex: "prometheus-stack;node-exporter"
        action: keep
      - source_labels:
          - __meta_docker_container_name
        target_label: container_name
        regex: /(.*)
        action: replace
    metric_relabel_configs:
      - source_labels:
          - __name__
          - mountpoint
        action: drop
        regex: "^node_filesystem.+;(/Applications|/Library|/Volumes)"